.\""Copyright (c) 2013 Apple, Inc. All Rights Reserved.
.Dd March 16, 2013
.Dt WARMD_AGENT 8
.Os "Mac OS X"       
.Sh NAME
.Nm warmd_agent
.Nd general helper tool
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a helper tool for OS X.
.Pp
There are no configuration options to \fBwarmd_agent\fR.  Users should not run
.Nm 
manually.
