.TH "at_block_buffer_t" 3 "Thu Jul 14 2016" "Version AppleTextureEncoder-1.12.12" "AppleTextureEncoder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
at_block_buffer_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AppleTextureEncoder\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void *__nonnull \fBblocks\fP"
.br
.ti -1c
.RI "size_t \fBrowBytes\fP"
.br
.ti -1c
.RI "size_t \fBsliceBytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A rectangular region of input texels in a texel buffer\&. The Asize is inferred from the size of the corresponding \fBat_texel_region_t\fP, from which the data is taken\&. 
.SH "Member Data Documentation"
.PP 
.SS "void* __nonnull at_block_buffer_t::blocks"
A pointer to the top left corner of the region of block data to write after encoding\&. Must be 16-byte aligned\&. 
.SS "size_t at_block_buffer_t::rowBytes"
The number of bytes from the start of one row to the next\&. Must be a multiple of the block size\&. 
.SS "size_t at_block_buffer_t::sliceBytes"
The number of bytes from the start of one slice to the next\&. Must be a multiple of the block size\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AppleTextureEncoder from the source code\&.
