.Dd March 30, 2017
.Dt microstackshot 8
.Os
.Sh NAME
.Nm microstackshot
.Nd aggregates microstackshot call graphs
.Sh DESCRIPTION
The
.Nm
command aggregates and saves daily microstackshot call graphs to the diagnostic reports directory. The reports may be sent to Apple if the device is opted into data collection.
.Pp
This command works only within the context of a launchd job and should not be run from the command line.
