.TH "MPSNNStateNode" 3 "Sun Jul 2 2017" "Version MetalPerformanceShaders-84.1" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSNNStateNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MPSNNGraphNodes\&.h>\fP
.PP
Inherits NSObject\&.
.PP
Inherited by \fBMPSCNNConvolutionStateNode\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(nonnull instancetype) \- \fBinit\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "id< \fBMPSHandle\fP > \fBhandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A placeholder node denoting the position in the graph of a \fBMPSState\fP object  Some filters need additional information about an image in order to function\&. For example an unpooling max filter needs to know which position the max result came from in the original pooling filter in order to select the right data for unpooling\&. In other cases, state may be moved into a \fBMPSState\fP object in order to keep the filter itself immutable\&. The \fBMPSState\fP object typically encapsulates one or more MTLResource objects\&. 
.SH "Method Documentation"
.PP 
.SS "\- (nonnull instancetype) init "

.SH "Property Documentation"
.PP 
.SS "\- (id<\fBMPSHandle\fP>) handle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"
MPS resource identification  See \fBMPSHandle\fP protocol reference\&. Default: nil 

.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
