.TH RSA_SecurID_getpasswd 1 "February 2008"
.SH NAME
RSA_SecurID_getpasswd \- get the one-use password from a RSA sid-800
token
.
.SH SYNOPSIS
.B RSA_SecurID_getpasswd
.
.SH DESCRIPTION
RSA_SecurID_getpasswd sends to stdout the one-use password also
displayed on the screen of a RSA sid-800 USB token.
.
.SH AUTHOR
Ludovic Rousseau <ludovic.rousseau@free.fr>
