'\" e  
'\"macro stdmacro
.ds Vn Version 1.2
.ds Dt 24 September 1999
.ds Re Release 1.2.1
.ds Dp May 22 14:45
.ds Dm 3 May 22 14:
.ds Xs 34777     3
.TH GLISTEXTURE 3G
.SH NAME
.B "glIsTexture
\- determine if a name corresponds to a texture

.SH C SPECIFICATION
GLboolean \f3glIsTexture\fP(
GLuint \fItexture\fP )
.nf
.fi

.SH PARAMETERS
.TP \w'\f2texture\fP\ \ 'u 
\f2texture\fP
Specifies a value that may be the name of a texture.
.SH DESCRIPTION
\%\f3glIsTexture\fP returns \%\f3GL_TRUE\fP if \f2texture\fP is currently the name of a texture.
If \f2texture\fP is zero, or is a non-zero value that is not currently the
name of a texture, or if an error occurs, \%\f3glIsTexture\fP returns \%\f3GL_FALSE\fP.
.SH NOTES
\%\f3glIsTexture\fP is available only if the GL version is 1.1 or greater.
.SH ERRORS
\%\f3GL_INVALID_OPERATION\fP is generated if \%\f3glIsTexture\fP is executed
between the execution of \%\f3glBegin\fP and the corresponding
execution of \%\f3glEnd\fP.
.SH SEE ALSO
\%\f3glBindTexture\fP,
\%\f3glCopyTexImage1D\fP,
\%\f3glCopyTexImage2D\fP,
\%\f3glDeleteTextures\fP,
\%\f3glGenTextures\fP,
\%\f3glGet\fP,
\%\f3glGetTexParameter\fP,
\%\f3glTexImage1D\fP,
\%\f3glTexImage2D\fP,
\%\f3glTexImage3D\fP,
\%\f3glTexParameter\fP
