.TH "MPSImageReadWriteParams" 3 "Mon Jul 9 2018" "Version MetalPerformanceShaders-119.3" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSImageReadWriteParams
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MPSImage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NSUInteger \fBfeatureChannelOffset\fP"
.br
.ti -1c
.RI "NSUInteger \fBnumberOfFeatureChannelsToReadWrite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
these parameters are passed in to allow user to read/write to a particular set of featureChannels in an \fBMPSImage\fP 
.SH "Member Data Documentation"
.PP 
.SS "NSUInteger MPSImageReadWriteParams::featureChannelOffset"
featureChannel offset from which to read/write featureChannels, this should be a multiple of 4 
.SS "NSUInteger MPSImageReadWriteParams::numberOfFeatureChannelsToReadWrite"
is number of featureChannels, should be greater than 0 and multiple of 4 unless featureChannelOffset is 0 

.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
