.\"
.\"  cc_fips_test.1
.\"  corecrypto
.\"
.\"  Created on 02/02/2012
.\"
.\"  Copyright (c) 2012,2017 Apple Inc. All rights reserved.
.\"
.Dd 02/02/12
.Dt cc_fips_test 1
.Os Darwin
.Sh NAME
.Nm cc_fips_test
.Nd Validates correctness of the corecrypto library during bootup
.Sh DESCRIPTION
The
.Nm
performs a basic POST validation pass on the
.Ar corecrypto
dynamic library loaded by the operating system during the early boot cycle.  This command is called by
.Ar launchd
and will return a non-zero error code if the system fails the tests.
