'\" te  
'\"macro stdmacro
.ds Vn Version 1.2
.ds Dt 24 September 1999
.ds Re Release 1.2.1
.ds Dp May 22 14:45
.ds Dm 4 May 22 14:
.ds Xs 23505     6
.TH GLGETPIXELMAP 3G
.SH NAME
.B "glGetPixelMapfv, glGetPixelMapuiv, glGetPixelMapusv
\- return the specified pixel map

.SH C SPECIFICATION
void \f3glGetPixelMapfv\fP(
GLenum \fImap\fP,
.nf
.ta \w'\f3void \fPglGetPixelMapfv( 'u
	GLfloat \fI*values\fP )
.fi
void \f3glGetPixelMapuiv\fP(
GLenum \fImap\fP,
.nf
.ta \w'\f3void \fPglGetPixelMapuiv( 'u
	GLuint \fI*values\fP )
.fi
void \f3glGetPixelMapusv\fP(
GLenum \fImap\fP,
.nf
.ta \w'\f3void \fPglGetPixelMapusv( 'u
	GLushort \fI*values\fP )
.fi

.SH PARAMETERS
.TP \w'\fIvalues\fP\ \ 'u 
\f2map\fP
Specifies the name of the pixel map to return.
Accepted values are
\%\f3GL_PIXEL_MAP_I_TO_I\fP,
\%\f3GL_PIXEL_MAP_S_TO_S\fP,
\%\f3GL_PIXEL_MAP_I_TO_R\fP,
\%\f3GL_PIXEL_MAP_I_TO_G\fP,
\%\f3GL_PIXEL_MAP_I_TO_B\fP,
\%\f3GL_PIXEL_MAP_I_TO_A\fP,
\%\f3GL_PIXEL_MAP_R_TO_R\fP,
\%\f3GL_PIXEL_MAP_G_TO_G\fP,
\%\f3GL_PIXEL_MAP_B_TO_B\fP, and
\%\f3GL_PIXEL_MAP_A_TO_A\fP.
.TP
\f2values\fP
Returns the pixel map contents.
.SH DESCRIPTION
See the \%\f3glPixelMap\fP reference page for a description of the acceptable
values for the \f2map\fP parameter.
\%\f3glGetPixelMap\fP returns in \f2values\fP the contents of the pixel map
specified in \f2map\fP.
Pixel maps are used during the execution of
\%\f3glReadPixels\fP,
\%\f3glDrawPixels\fP,
\%\f3glCopyPixels\fP,
\%\f3glTexImage1D\fP,
\%\f3glTexImage2D\fP,
\%\f3glTexImage3D\fP,
\%\f3glTexSubImage1D\fP,
\%\f3glTexSubImage2D\fP,
\%\f3glTexSubImage3D\fP,
\%\f3glCopyTexImage1D\fP,
\%\f3glCopyTexImage2D\fP,
\%\f3glCopyTexSubImage1D\fP,
\%\f3glCopyTexSubImage2D\fP,
\%\f3glCopyTexSubImage3D\fP,
\%\f3glColorTable\fP,
\%\f3glColorSubTable\fP,
\%\f3glCopyColorTable\fP,
\%\f3glCopyColorSubTable\fP,
\%\f3glConvolutionFilter1D\fP,
\%\f3glConvolutionFilter2D\fP,
\%\f3glSeparableFilter2D\fP,
\%\f3glGetHistogram\fP,
\%\f3glGetMinmax\fP, and
\%\f3glGetTexImage\fP
to map color indices,
stencil indices,
color components,
and depth components to other values.
.P
Unsigned integer values,
if requested,
are linearly mapped from the internal fixed or floating-point representation
such that 1.0 maps to the largest representable integer value,
and 0.0 maps to 0.
Return unsigned integer values are undefined if the map value was
not in the range [0,1].
.P
To determine the required size of \f2map\fP,
call \%\f3glGet\fP with the appropriate symbolic constant.
.SH NOTES
If an error is generated,
no change is made to the contents of \f2values\fP.
.SH ERRORS
\%\f3GL_INVALID_ENUM\fP is generated if \f2map\fP is not an accepted value.
.P
\%\f3GL_INVALID_OPERATION\fP is generated if \%\f3glGetPixelMap\fP
is executed between the execution of \%\f3glBegin\fP
and the corresponding execution of \%\f3glEnd\fP.
.SH ASSOCIATED GETS
.na
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_I_TO_I_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_S_TO_S_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_I_TO_R_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_I_TO_G_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_I_TO_B_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_I_TO_A_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_R_TO_R_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_G_TO_G_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_B_TO_B_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_PIXEL_MAP_A_TO_A_SIZE\fP
.br
\%\f3glGet\fP with argument \%\f3GL_MAX_PIXEL_MAP_TABLE\fP
.SH SEE ALSO
\%\f3glColorSubTable\fP,
\%\f3glColorTable\fP,
\%\f3glConvolutionFilter1D\fP,
\%\f3glConvolutionFilter2D\fP,
\%\f3glCopyColorSubTable\fP,
\%\f3glCopyColorTable\fP,
\%\f3glCopyPixels\fP,
\%\f3glCopyTexImage1D\fP,
\%\f3glCopyTexImage2D\fP,
\%\f3glCopyTexSubImage1D\fP,
\%\f3glCopyTexSubImage2D\fP,
\%\f3glCopyTexSubImage3D\fP,
\%\f3glDrawPixels\fP,
\%\f3glGetHistogram\fP,
\%\f3glGetMinmax\fP,
\%\f3glGetTexImage\fP,
\%\f3glPixelMap\fP,
\%\f3glPixelTransfer\fP,
\%\f3glReadPixels\fP,
\%\f3glSeparableFilter2D\fP,
\%\f3glTexImage1D\fP,
\%\f3glTexImage1D\fP,
\%\f3glTexImage2D\fP
\%\f3glTexImage2D\fP,
\%\f3glTexImage3D\fP,
\%\f3glTexSubImage1D\fP,
\%\f3glTexSubImage2D\fP,
\%\f3glTexSubImage3D\fP
