.TH "MPSIntegerDivisionParams" 3 "Mon Jul 9 2018" "Version MetalPerformanceShaders-119.3" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSIntegerDivisionParams
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MPSKernelTypes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBdivisor\fP"
.br
.ti -1c
.RI "uint16_t \fBrecip\fP"
.br
.ti -1c
.RI "uint16_t \fBaddend\fP"
.br
.ti -1c
.RI "uint16_t \fBshift\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the [[function_constant(index)]] index where the kMPSConstant is passed to the kernel 
.SH "Member Data Documentation"
.PP 
.SS "uint16_t MPSIntegerDivisionParams::addend"

.SS "uint16_t MPSIntegerDivisionParams::divisor"

.SS "uint16_t MPSIntegerDivisionParams::recip"

.SS "uint16_t MPSIntegerDivisionParams::shift"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
