.Dd April 29, 2010
.Dt mdmclient 1
.Os MacOSX
.Sh NAME
.Nm mdmclient
.Nd MDM (Mobile Device Management) client
.Pp
.Sh DESCRIPTION
.Nm
.Pp
Used internally for communication with Mobile Device Management (Profile Manager) server. Receives configuration profiles and commands from the server after a user binds to the server by installing a binding profile. Part of Managed Client (MCX).
