.Dd September 6, 2010
.Os Darwin
.Dt OD_USER_HOMES 8
.Sh NAME
.Nm od_user_homes
.Nd executable map program for auto_home records synthesized from user records
.Sh SYNOPSIS
.Nm /usr/libexec/od_user_homes
.Op Ar username
.Sh DESCRIPTION
.Nm
is a program that takes a user name specified by
.Ar username
and, if there's a user record for that user in Open Directory,
and that user record contains a HomeDirectory attribute,
and the <path> portion of the HomeDirectory attribute is empty or just /,
prints the URL from that attribute, and exits with an exit status of 0.
If there is no user record for that user, or the user record doesn't
contain a HomeDirectory attribute, or the <path> portion is neither
empty nor just /, or if an error occurs, nothing is printed, and
.Nm
exits with a user status of 1.
This is intended to be used as an executable map for auto_home.
.Sh SEE ALSO
.Xr auto_master 5 ,
.Xr automountd 8
