.Dd May 04, 2011
.Dt taskgated-helper 8
.Os
.Sh NAME
.Nm taskgated-helper
.Nd taskgated helper process
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility is used by taskgated for various functions.
.Sh NOTE
The
.Nm
utility should not be invoked directly.  It is intended
only for use by taskgated.
.Sh SEE ALSO
.Xr profiles 1 ,
.Xr taskgated 8
