.\"
.\" Copyright (c) 2020 Apple Computer, Inc.  All rights reserved.
.\"
.Dd July 29, 2020
.Dt APFS_SYSTEMSNAPSHOT 8
.Os
.Sh NAME
.Nm apfs_systemsnapshot
.Nd create and tag APFS system snapshots
.Sh SYNOPSIS
.Nm
.Fl r Ar snapshot_name
.Fl v Ar mount_point
.Nm
.Fl s Ar snapshot_name
.Fl v Ar mount_point
.Nm
.Fl h
.Sh DESCRIPTION
The
.Nm
utility can create or tag a new snapshot of a Signed System Volume.
.Pp
.Nm
requires disabling the authenticated-root System Integrity Protection configuration from recoveryOS.
Once disabled, non-sealed snapshots can be created and tagged as the snapshot to be rooted from.
.Pp
.Nm
should not be used when working on kernel extension development,
.Xr bless 8
should be used instead.
.Pp
The
.Ar mount_point
parameter should be the mount point of a Signed System Volume.
.Pp
The options are as follows:
.Bl -tag -width 20n
.It Fl r Ar snapshot_name
Tag
.Pa snapshot_name
as the root snapshot to boot from upon next boot.
.It Fl s Ar snapshot_name
Create a new system snapshot named
.Pa snapshot_name .
.It Fl h
Print a usage message.
.El
.Sh EXIT STATUS
.Nm
exits with 0 on success, and >0 if an error occurs.
.Sh SEE ALSO
.Xr bless 8 ,
.Xr csrutil 8 ,
.Xr diskutil 8
.Sh HISTORY
The
.Nm
utility was introduced in macOS 11.
