.Dd November 11, 2016
.Dt AppleCameraAssistant 8
.Os
.Sh NAME
.Nm AppleCameraAssistant
.Nd CoreMediaIO DAL Assistant Process.
.Sh DESCRIPTION
.Nm
is used by the CoreMediaIO Device Abstraction Layer Plug-In that provides video capture from some models of Apple FaceTime cameras using AVFoundation Capture APIs.  The process allows multiple applications to simultaneously capture from the same camera.