.\" Copyright (c) 2012 Apple Inc. All rights reserved.
.Dd Nov. 11, 2011
.Dt "DevToolsSecurity" 8
.Os
.Sh NAME
.Nm DevToolsSecurity
.Nd Change the security authorization policies for developer systems
.Sh SYNOPSIS
.Nm
.Nm DevToolsSecurity
.Op Fl status
.Op Fl enable
.Op Fl disable
.Op Fl verbose
.Sh DESCRIPTION
This tool changes the security authorization policies for use of Apple-code-signed debugger and performance analysis tools on development systems.
.Pp
On normal user systems, the first time in a given login session that any such Apple-code-signed debugger or performance analysis tools are used to examine one of the user's processes, the user is queried for an administator password for authorization.
.Nm
tool to change the authorization policies, such that a user who is a member of either the admin group or the _developer group does not need to enter an additional password to use the Apple-code-signed debugger or performance analysis tools.
.Pp
Developers will typically not need to run this tool manually.  If for some reason it needs to be run manually, it can be run from /usr/sbin.
