.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd January 17th, 2011
.Dt FDERECOVERYAGENT 8
.Os "OS X"
.Sh NAME
.Nm FDERecoveryAgent
.Nd Full Disk Encryption Key Recovery Transmission Agent
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
sends encrypted CoreStorage key recovery information to Apple.  It is run only when "Store
the recovery key with Apple" is selected, and even then only if the information
could not be transmitted when that option was first selected.
.Pp
.Sh FILES
.Pa /System/Library/LaunchDaemons/com.apple.security.FDERecoveryAgent.plist
.Sh SEE ALSO 
.Xr diskutil 8
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner 
