.\"
.\" Copyright (c) 2005 Apple Computer, Inc.  All rights reserved.
.\"
.Dd October 25, 2005
.Dt UPSSHUTDOWN 8
.Os Darwin
.Sh NAME
.Nm upsshutdown
.Nd UPS emergency low power shutdown script
.Sh DESCRIPTION
.Nm
is a script that runs automatically when the system performs an emergency
UPS low power shutdown.  The script is run before
.Xr shutdown 8
is invoked.
.Nm
only runs if one of the three shutdown rules is enabled and true:
"percentage remaining," "time remaining," or "time since loss of power."
These settings can be changed using
.Xr pmset 1
or Energy Saver in System Preferences.
.Pp
The system administrator may modify
.Ns Nm .
The script should only contain commands that must run in the case of an
emergency UPS shutdown.  It should not contain any commands that would
otherwise be executed during a normal shutdown since the normal shutdown
procedure follows invocation of
.Ns Nm .
.Sh LOCATION
.Pa /usr/libexec/upsshutdown
.Sh SEE ALSO
.Xr pmset 1 ,
.Xr ioupsd 8
