.\" 
.\" Copyright (c) 2006-2017 Apple Inc. All rights reserved.
.\" 
.Dd March 9, 2017
.Dt SANDBOX-EXEC 1
.Os "Mac OS X"
.Sh NAME
.Nm sandbox-exec
.Nd execute within a sandbox (DEPRECATED)
.Sh SYNOPSIS
.Nm
.Op Fl f Ar profile-file
.Op Fl n Ar profile-name
.Op Fl p Ar profile-string
.Op Fl D Ar key\fR=\f[]value ...
.Ar command
.Op Ar arguments ...
.Sh DESCRIPTION
The
.Nm
command is
.Sy DEPRECATED .
Developers who wish to sandbox an app should instead adopt the App Sandbox feature described in the App Sandbox Design Guide.
The
.Nm
command enters a sandbox using a profile specified by the
.Fl f ,
.Fl n ,
or
.Fl p
option and executes
.Ar command
with
.Ar arguments .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar profile-file
Read the profile from the file named
.Ar profile-file .
.It Fl n Ar profile-name
Use the pre-defined profile
.Ar profile-name .
.It Fl p Ar profile-string
Specify the profile to be used on the command line.
.It Fl D Ar key\fR=\f[]value
Set the profile parameter
.Ar key
to
.Ar value .
.El
.Sh SEE ALSO
.Xr sandbox_init 3 ,
.Xr sandbox 7 ,
.Xr sandboxd 8
