.TH "<MPSHandle >" 3 "Mon Jul 9 2018" "Version MetalPerformanceShaders-119.3" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<MPSHandle >
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MPSNNGraphNodes\&.h>\fP
.PP
Inherits <NSSecureCoding>, and <NSObject>\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(NSString *__nullable) \- \fBlabel\fP"
.br
.in -1c
.SH "Method Documentation"
.PP 
.SS "\- (NSString * __nullable \fBMPSHandle\fP) label \fC [required]\fP"
\fBA\fP label to be attached to associated MTLResources for this node 
.PP
\fBReturns:\fP
.RS 4
\fBA\fP human readable string for debugging purposes 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
