.Dd September 1, 2005
.Dt mdutil 1
.Os Mac\ OS X
.Sh NAME
.Nm mdutil
.Nd manage the metadata stores used by Spotlight
.Sh SYNOPSIS
.Nm
.Op Fl pEsav
.Op Fl i Ar on | off
.Ar mountPoint ...
.Sh DESCRIPTION
The
.Nm
command is useful for managing the metadata stores for mounted volumes.
.Pp
The following options are available:
.Bl -tag -width -a
.It Fl p 
Spotlight caches indexes of some network devices locally.
This option requests that a local caches be flushed to the appropriate network device.
.It Fl E
This flag will cause each local store for the volumes indicated to be erased.
The stores will be rebuilt if appropriate.
.It Fl i Ar on | off
Sets the indexing status for the provided volumes to on or off.
Note that indexing may be delayed due to low disk space or other conditions.
.It Fl d 
Disables Spotlight searches on the provided volume.
.It Fl s 
Display the indexing status of the listed volumes.
.It Fl a 
Apply command to all volumes.
.It Fl v 
Print verbose information when available.
.El
.Sh SEE ALSO
.Xr mdfind 1 ,
.Xr mds 8 ,
.Xr mdimport 1
