.Dd 4/5/10
.Dt nettop 1
.Os Darwin
.\"---------
.Sh NAME
.\"---------
.Nm nettop
.Nd Display updated information about the network
.\"---------
.Sh SYNOPSIS
.\"---------
.Nm
.Op Fl nc
.Op Fl m Ar <mode>
.\"---------
.Sh DESCRIPTION
.\"---------
The
.Nm
program displays a list of sockets or routes. The counts for network
structures are updated periodically. While the program is running the following
keys may be used:
.Bl -tag -width -indent
.It Cm q
Quit
.It Cm Up Arrow
Scroll up
.It Cm Down Arrow
Scroll down
.It Cm Right Arrow
Scroll Right
.It Cm Left Arrow
Scroll Left
.It Cm d
Toggle delta output
.It Cm r
Redraw screen
.It Cm p
Toggle human readable numbers
.It Cm e
Expand all
.It Cm c
Collapse all
.It Cm h
Bring up the help menu
.It Cm j
Bring up the column selection menu.
In this mode you can enable/disable columns and change their order.
.El
.\"---------
.Sh OPTIONS
.\"---------
A list of flags and their descriptions:
.Bl -tag -width -indent
.It Fl m Ar <mode>
Specify the mode. By default, nettop will monitor TCP and UDP sockets. The
following modes are supported:
.Bl -tag -width -indent
.It Cm tcp
Only TCP sockets will be monitored
.It Cm udp
Only UDP sockets will be monitored
.It Cm route
Instead of sockets, the routing table will be monitored
.El
.It Fl n
Disable address to name resolution
.It Fl c
Less intensive use of the CPU - draws less often
.El
.\"---------
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\"---------
.\"---------
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
.\"---------
