.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.Dd January 10, 2013     \" DATE 
.Dt security2 1          \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm security2
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd temporary adjunct to the security(1) command.
.Sh DESCRIPTION          \" Section Header - required - don't modify
This command is intended for internal testing of iCloud Keychain functionality.
.br
Invoke without any arguments to see usage.
.Pp
.Sh WARNING
*** APPLE INTERNAL USE ONLY - DO NOT DISTRIBUTE ***
.Pp
Do not rely on the existence of
.Nm
as it will be merged into security(1).
.br
See: <rdar://13071131>
.Pp
*** APPLE INTERNAL USE ONLY - DO NOT DISTRIBUTE ***
