.\" Copyright (c) 2010, Apple Inc.  All rights reserved.
.\"
.Dd October 28, 2010
.Dt TRACE 1
.Os "Mac OS X"
.Sh NAME
.Nm trace
.Nd configure and record kernel trace events
.Sh SYNOPSIS
.Nm trace
.Fl h
.Pp
.Nm trace
.Fl i
.Op Fl b Ar numbufs
.Pp
.Nm trace
.Fl g
.Pp
.Nm trace
.Fl d
.Op Fl a Ar pid | Fl x Ar pid
.Pp
.Nm trace
.Fl r
.Pp
.Nm trace
.Fl n
.Pp
.Nm trace
.Fl e
.Op Fl c Ar class Oo Fl p Ar class Oc Oo Fl s Ar subclass Oc
.Op Fl a Ar pid | Fl x Ar pid
.Op Fl k Ar code | Fl k Ar code | Fl k Ar code | Fl k Ar code
.Pp
.Nm trace
.Fl E
.Op Fl c Ar class Oo Fl p Ar class Oc Oo Fl s Ar subclass Oc
.Op Fl a Ar pid | Fl x Ar pid
.Op Fl k Ar code | Fl k Ar code | Fl k Ar code | Fl k Ar code
.Ar executable_path
.Op Ar optional args to executable
.Pp
.Nm trace
.Fl t
.Op Fl R Ar rawfile
.Op Fl o Ar OutputFilename
.Op Fl N
.Op Ar ExtraCodeFilename1 ExtraCodeFilename2 ...
.Sh DESCRIPTION
The
.Nm trace
command allows developers to initialize and configure
the kernel trace subsystem. Trace events can be recorded
to an in-memory buffer, or logged directly to a file. Raw
data files can later be decoded to a plaintext format.
.Sh SEE ALSO
.Xr fs_usage 1 ,
.Xr sc_usage 1 ,
.Xr latency 1 ,
.Xr top 1
