.\""Copyright (c) 2013-2013 Apple Computer, Inc. All Rights Reserved.
.Dd February 1, 2013
.Dt APPSLEEPD 8
.Os "Mac OS X"
.Sh NAME
.Nm appsleepd
.Nd app sleep daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
provides app sleep services.
.Pp
There are no configuration options to \fBappsleepd\fR.  Users should not run 
.Nm 
manually.
