.Dd November 02, 2016
.Dt PLMU 8
.Os macOS
.Sh NAME
.Nm "Photo Library Migration Utility"
.Nd Upgrade historical iPhoto/Aperture libraries
.Sh DESCRIPTION
.Nm
prepares a clone of an iPhoto/Aperture library for migration to Photos. If required, an upgrade and rebuild will be performed on the cloned library. The utility is for Photos.app use only.
.Sh SEE ALSO
.Xr cloudphotosd 8 ,
.Xr photoanalysisd 8 ,
.Xr photolibraryd 8
