'\" e  
'\"macro stdmacro
.ds Vn Version 1.2
.ds Dt 6 March 1997
.ds Re Release 1.2.0
.ds Dp May 22 14:54
.ds Dm 0 May 22 14:
.ds Xs 53296     3
.TH GLUNEWNURBSRENDERER 3G
.SH NAME
.B "gluNewNurbsRenderer
\- create a NURBS object

.SH C SPECIFICATION
GLUnurbs* \f3gluNewNurbsRenderer\fP( void )
.nf
.fi

.SH DESCRIPTION
\%\f3gluNewNurbsRenderer\fP creates and returns a pointer to
a new NURBS object.
This object must be referred to when calling
NURBS rendering and control functions. A return value of
0 means that there is not enough memory to allocate the object.
.SH SEE ALSO
\%\f3gluBeginCurve\fP, \%\f3gluBeginSurface\fP, \%\f3gluBeginTrim\fP, \%\f3gluDeleteNurbsRenderer\fP, \%\f3gluNurbsCallback\fP, \%\f3gluNurbsProperty\fP

