.\" Copyright (c) 2015 Apple Inc. All rights reserved.
.Dd 03/01/15
.Dt os_log_create 3
.Os Darwin
.Sh NAME
.Nm os_log_create
.Nd create an object that tracks the state of logging for a given system.
.Sh SYNOPSIS
.In os/log.h
.Ft os_log_t
.Fn os_log_create "const char *subsystem" "const char *category"
.Sh DESCRIPTION
.Pp
Use
.Nm os_log_create
to create an object that can be passed to
.Xr os_log 3
calls.
Log messages to this object will be marked with the object's subsystem and category name.
The behavior of log messages to this object can be configured using the
.Xr log 1
command.
.Pp
.Sh EXAMPLES
Create a new os_log_t object and log a message:
.Pp
.Bd -literal -offset indent
#include <os/log.h>

/* create a log object for the subsystem, specifically the "connections" category" */
os_log_t log = os_log_create("com.example.widget", "connections");

/* log a connection related message */
os_log(log, "connection state changed: %d interface: %s", if, interface);
.Ed
.Pp
.Sh SEE ALSO
.Xr log 1 ,
.Xr os_log 3
