.\" -*- nroff -*-
.\" 
.\" Copyright (c) 2001 Carnegie Mellon University.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer. 
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" 3. The name "Carnegie Mellon University" must not be used to
.\"    endorse or promote products derived from this software without
.\"    prior written permission. For permission or any other legal
.\"    details, please contact  
.\"      Office of Technology Transfer
.\"      Carnegie Mellon University
.\"      5000 Forbes Avenue
.\"      Pittsburgh, PA  15213-3890
.\"      (412) 268-4387, fax: (412) 268-7395
.\"      tech-transfer@andrew.cmu.edu
.\"
.\" 4. Redistributions of any form whatsoever must retain the following
.\"    acknowledgment:
.\"    "This product includes software developed by Computing Services
.\"     at Carnegie Mellon University (http://www.cmu.edu/computing/)."
.\"
.\" CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
.\" THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
.\" FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
.\" AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\" 
.TH sasl_getrealm_t 3 "10 July 2001" SASL "SASL man pages"
.SH NAME
sasl_getrealm_t \- Realm Acquisition Callback

.SH SYNOPSIS
.nf
.B #include <sasl/sasl.h>

.sp
.BI "int sasl_getrealm_t(void " *context ", int " id ", "
.BI "			 const char " **availrealms ","
.BI "                    const char " **result ")"

.fi
.SH DESCRIPTION

.B sasl_getrealm_t
is used when there is an interaction with SASL_CB_GETREALM as the type.

If a mechanism would use this callback, but it is not present, then the first
realm listed is automatically selected.  (Note that a mechanism may still
force the existence of a getrealm callback by SASL_CB_GETREALM to its
required_prompts list).

.I context
context from the callback record

.I id
callback ID (SASL_CB_GETREALM)

.I availrealms
A string list of the available realms.  NULL terminated, may be empty.

.I result
The chosen realm. (a NUL terminated string)

.SH "RETURN VALUE"
SASL callback functions should return SASL return codes. See sasl.h for a complete list. SASL_OK indicates success.

.SH "SEE ALSO"
sasl(3), sasl_callbacks(3)
