.
.TH "AEServer" "" "January 2017"
.
.SH "NAME"
\fBAEServer\fR
.
.P
AEServer(8) \-\- System\-wide daemon which recevies incoming (remote) AppleEvents
.
.SH "DESCRIPTION"
AEServer acts as a system\-wide daemon when Remote AppleEvents is enabled, allowing other computers to send AppleEvents to applications on this machine\.
.IP "" 0
.
.SH "SEE ALSO"
\fBaeutil\fR, 
\fBappeleventsd\fR
.
.SH "FILES"
\fI/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Support/AEServer\fR
.
.P
\fI/System/Library/LaunchDaemons/com\.apple\.eppc\.appleevents\.plist\fR
