.\"
.\" Copyright (c) 2012 Apple Inc. All rights reserved.
.\"
.\"
.Dd Feb 2, 2012
.Dt KCPROXY 8
.Os "Mac OS X"
.Sh NAME
.Nm kcproxy
.Nd Keychain Proxy
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
spawned by launchd to handle privileged keychain operations with appropriate authorization.
.Pp
This command is not intended to be invoked directly.
.Sh SEE ALSO
