.\" Copyright (c) 2014 Apple Inc. All rights reserved.
.Dd 23 April, 2014
.Dt amfid 8
.Os Darwin
.Sh NAME
.Nm amfid
.Nd The mobile file integrity daemon.
.Sh DESCRIPTION
.Nm
amfid is a daemon that checks the integrity of files running on the system.
It is not intended to be invoked directly.
.Sh SEE ALSO
.Xr launchd 8
.Xr launchd.conf 5
