.\" Copyright (c) © 2013 Apple Inc.
.Dd January 2013
.Dt networkd_privileged 8
.Os Darwin
.\"
.Sh NAME
.Nm networkd_privileged
.Nd networkd privileged helper.
.\" 
.Sh SYNOPSIS
.Nm
.\"
.Sh DESCRIPTION
.Nm
is a launch-on-demand daemon that performs privileged opreations on behalf of
.Xr networkd 8 .
.Pp
.Nm
has no user-specifiable command-line argument, and users should not run
.Nm
manually.
.Pp
.\"
.Sh FILES
.Bl -tag -width 10
.It Pa /usr/libexec/networkd_privileged
The binary.
.It Pa /System/Library/LaunchDaemons/com.apple.networkd_privileged.plist
The
.Xr launchd.plist 5
controlling the
.Nm
job.
.El
.\"
.Sh BUGS
.Nm
bugs are tracked in Apple Radar component "networkd".
.\"
.Sh HISTORY
.Nm
first appeared in Mac OS X 10.8.
.\"
.Sh SEE ALSO
.Xr networkd 8 ,
.Xr launchd.plist 5
