.\" Copyright (c) 2017 Apple Inc. All rights reserved.
.\"
.\" The contents of this file constitute Original Code as defined in and
.\" are subject to the Apple Public Source License Version 1.1 (the
.\" "License").  You may not use this file except in compliance with the
.\" License.  Please obtain a copy of the License at
.\" http://www.apple.com/publicsource and read it before using this file.
.\"
.\" This Original Code and all software distributed under the License are
.\" distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER
.\" EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
.\" INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT.  Please see the
.\" License for the specific language governing rights and limitations
.\" under the License.
.\"
.\"     @(#)apfsd.8
.Dd August 8th, 2017
.Dt APFSD 8
.Os "OS X"
.Sh NAME
.Nm apfsd
.Sh SYNOPSIS
.Nm
.Nd APFS volume manager
.Sh DESCRIPTION
.Nm
is the APFS volume management daemon, it controls volume encryption and decryption, automatic file defragmentation and performs other housekeeping duties as necessary.
.Pp
.Nm
is invoked invoked by launchd(8) when presence of APFS volume is detected.
.Pp
.Sh FILES
.Pa /System/Library/LaunchDaemons/com.apple.apfsd.plist
.Sh SEE ALSO 
.Xr diskutil 8
