.\"
.\" Copyright (c) 2006-2015 Apple Inc. All rights reserved.
.\"
.Dd July 29, 2008
.Dt SANDBOXD 8
.Os "Mac OS X"
.Sh NAME
.Nm sandboxd
.Nd sandbox daemon
.Sh SYNOPSIS
.Nm
.Op s
.Nm
.Sh DESCRIPTION
.Nm
performs services on behalf of the Sandbox kernel extension.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl b
Just log basic sandbox violation information without a backtrace.
.It Fl s
Do not symbolicate backtraces.
.El
.Pp
This command is not intended to be invoked directly.
.Sh SEE ALSO
.Xr sandbox-exec 1 ,
.Xr sandbox_init 3 ,
.Xr sandbox 7
