.Dd September 20, 2010 
.Dt installer-core 8 
.Os Mac OS X
.\"																				NAME 
.Sh NAME
.Nm installer-core
.Nd helper for installer tool
.\"																				SYNOPSIS
.Sh SYNOPSIS
.Nm
.\"																				DESCRIPTION
.Sh DESCRIPTION
.Nm
is used by 
.Xr installer 8 .
It is not meant to be invoked directly.
.\"																				SEE ALSO 
.Sh SEE ALSO 
.Xr installer 8
