/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H_TMP
#define	_PROBES_H_TMP

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define TRACE_POSTGRESQL_STABILITY "___dtrace_stability$postgresql$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define TRACE_POSTGRESQL_TYPEDEFS "___dtrace_typedefs$postgresql$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__checkpoint__done$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__checkpoint__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__checkpoint__start$v1$696e74(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__checkpoint__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__checkpoint__sync__start$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__checkpoint__sync__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_FLUSH_DONE(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__flush__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_FLUSH_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__flush__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_FLUSH_START(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__flush__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_FLUSH_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__flush__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_READ_DONE(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__read__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74$63686172$63686172(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_READ_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__read__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_READ_START(arg0, arg1, arg2, arg3, arg4, arg5, arg6) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__read__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74$63686172(arg0, arg1, arg2, arg3, arg4, arg5, arg6); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_READ_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__read__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_SYNC_DONE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__sync__done$v1$696e74$696e74$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__sync__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_SYNC_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__sync__start$v1$696e74$696e74(arg0, arg1); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__sync__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__sync__written$v1$696e74(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__sync__written$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__write__dirty__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__write__dirty__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$buffer__write__dirty__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$buffer__write__dirty__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_CHECKPOINT_DONE(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$checkpoint__done$v1$696e74$696e74$696e74$696e74$696e74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_CHECKPOINT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$checkpoint__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_CHECKPOINT_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$checkpoint__start$v1$696e74(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_CHECKPOINT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$checkpoint__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$clog__checkpoint__done$v1$63686172(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$clog__checkpoint__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_CLOG_CHECKPOINT_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$clog__checkpoint__start$v1$63686172(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_CLOG_CHECKPOINT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$clog__checkpoint__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_DEADLOCK_FOUND() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$deadlock__found$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_DEADLOCK_FOUND_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$deadlock__found$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_LOCK_WAIT_DONE(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$lock__wait__done$v1$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74(arg0, arg1, arg2, arg3, arg4, arg5); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_LOCK_WAIT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$lock__wait__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_LOCK_WAIT_START(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$lock__wait__start$v1$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74(arg0, arg1, arg2, arg3, arg4, arg5); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_LOCK_WAIT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$lock__wait__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_LWLOCK_ACQUIRE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$lwlock__acquire$v1$696e74$696e74(arg0, arg1); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_ACQUIRE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$lwlock__acquire$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$lwlock__condacquire$v1$696e74$696e74(arg0, arg1); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$lwlock__condacquire$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$lwlock__condacquire__fail$v1$696e74$696e74(arg0, arg1); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$lwlock__condacquire__fail$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_LWLOCK_RELEASE(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$lwlock__release$v1$696e74(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_RELEASE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$lwlock__release$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_LWLOCK_WAIT_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$lwlock__wait__done$v1$696e74$696e74(arg0, arg1); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_WAIT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$lwlock__wait__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_LWLOCK_WAIT_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$lwlock__wait__start$v1$696e74$696e74(arg0, arg1); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_WAIT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$lwlock__wait__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$multixact__checkpoint__done$v1$63686172(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$multixact__checkpoint__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$multixact__checkpoint__start$v1$63686172(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$multixact__checkpoint__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_DONE(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__done$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_EXECUTE_DONE() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__execute__done$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_EXECUTE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__execute__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_EXECUTE_START() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__execute__start$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_EXECUTE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__execute__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_PARSE_DONE(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__parse__done$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_PARSE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__parse__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_PARSE_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__parse__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_PARSE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__parse__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_PLAN_DONE() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__plan__done$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_PLAN_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__plan__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_PLAN_START() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__plan__start$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_PLAN_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__plan__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_REWRITE_DONE(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__rewrite__done$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_REWRITE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__rewrite__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_REWRITE_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__rewrite__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_REWRITE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__rewrite__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_QUERY_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$query__start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_QUERY_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$query__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_SMGR_MD_READ_DONE(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$smgr__md__read__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74$696e74$696e74(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_SMGR_MD_READ_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$smgr__md__read__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_SMGR_MD_READ_START(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$smgr__md__read__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74(arg0, arg1, arg2, arg3, arg4, arg5); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_SMGR_MD_READ_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$smgr__md__read__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$smgr__md__write__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74$696e74$696e74(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$smgr__md__write__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_SMGR_MD_WRITE_START(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$smgr__md__write__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74(arg0, arg1, arg2, arg3, arg4, arg5); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_SMGR_MD_WRITE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$smgr__md__write__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_SORT_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$sort__done$v1$63686172$6c6f6e67(arg0, arg1); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_SORT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$sort__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_SORT_START(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$sort__start$v1$696e74$63686172$696e74$696e74$63686172(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_SORT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$sort__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_STATEMENT_STATUS(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$statement__status$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_STATEMENT_STATUS_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$statement__status$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$subtrans__checkpoint__done$v1$63686172(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$subtrans__checkpoint__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$subtrans__checkpoint__start$v1$63686172(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$subtrans__checkpoint__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_TRANSACTION_ABORT(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$transaction__abort$v1$756e7369676e656420696e74(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_TRANSACTION_ABORT_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$transaction__abort$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_TRANSACTION_COMMIT(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$transaction__commit$v1$756e7369676e656420696e74(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_TRANSACTION_COMMIT_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$transaction__commit$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_TRANSACTION_START(arg0) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$transaction__start$v1$756e7369676e656420696e74(arg0); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_TRANSACTION_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$transaction__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$twophase__checkpoint__done$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$twophase__checkpoint__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$twophase__checkpoint__start$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$twophase__checkpoint__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$wal__buffer__write__dirty__done$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$wal__buffer__write__dirty__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$wal__buffer__write__dirty__start$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$wal__buffer__write__dirty__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_XLOG_INSERT(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$xlog__insert$v1$756e7369676e65642063686172$756e7369676e65642063686172(arg0, arg1); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_XLOG_INSERT_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$xlog__insert$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TRACE_POSTGRESQL_XLOG_SWITCH() \
do { \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_TYPEDEFS); \
	__dtrace_probe$postgresql$xlog__switch$v1(); \
	__asm__ volatile(".reference " TRACE_POSTGRESQL_STABILITY); \
} while (0)
#define	TRACE_POSTGRESQL_XLOG_SWITCH_ENABLED() \
	({ int _r = __dtrace_isenabled$postgresql$xlog__switch$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$postgresql$buffer__checkpoint__done$v1(void);
extern int __dtrace_isenabled$postgresql$buffer__checkpoint__done$v1(void);
extern void __dtrace_probe$postgresql$buffer__checkpoint__start$v1$696e74(int);
extern int __dtrace_isenabled$postgresql$buffer__checkpoint__start$v1(void);
extern void __dtrace_probe$postgresql$buffer__checkpoint__sync__start$v1(void);
extern int __dtrace_isenabled$postgresql$buffer__checkpoint__sync__start$v1(void);
extern void __dtrace_probe$postgresql$buffer__flush__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(int, unsigned int, unsigned int, unsigned int, unsigned int);
extern int __dtrace_isenabled$postgresql$buffer__flush__done$v1(void);
extern void __dtrace_probe$postgresql$buffer__flush__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(int, unsigned int, unsigned int, unsigned int, unsigned int);
extern int __dtrace_isenabled$postgresql$buffer__flush__start$v1(void);
extern void __dtrace_probe$postgresql$buffer__read__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74$63686172$63686172(int, unsigned int, unsigned int, unsigned int, unsigned int, int, char, char);
extern int __dtrace_isenabled$postgresql$buffer__read__done$v1(void);
extern void __dtrace_probe$postgresql$buffer__read__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74$63686172(int, unsigned int, unsigned int, unsigned int, unsigned int, int, char);
extern int __dtrace_isenabled$postgresql$buffer__read__start$v1(void);
extern void __dtrace_probe$postgresql$buffer__sync__done$v1$696e74$696e74$696e74(int, int, int);
extern int __dtrace_isenabled$postgresql$buffer__sync__done$v1(void);
extern void __dtrace_probe$postgresql$buffer__sync__start$v1$696e74$696e74(int, int);
extern int __dtrace_isenabled$postgresql$buffer__sync__start$v1(void);
extern void __dtrace_probe$postgresql$buffer__sync__written$v1$696e74(int);
extern int __dtrace_isenabled$postgresql$buffer__sync__written$v1(void);
extern void __dtrace_probe$postgresql$buffer__write__dirty__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(int, unsigned int, unsigned int, unsigned int, unsigned int);
extern int __dtrace_isenabled$postgresql$buffer__write__dirty__done$v1(void);
extern void __dtrace_probe$postgresql$buffer__write__dirty__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(int, unsigned int, unsigned int, unsigned int, unsigned int);
extern int __dtrace_isenabled$postgresql$buffer__write__dirty__start$v1(void);
extern void __dtrace_probe$postgresql$checkpoint__done$v1$696e74$696e74$696e74$696e74$696e74(int, int, int, int, int);
extern int __dtrace_isenabled$postgresql$checkpoint__done$v1(void);
extern void __dtrace_probe$postgresql$checkpoint__start$v1$696e74(int);
extern int __dtrace_isenabled$postgresql$checkpoint__start$v1(void);
extern void __dtrace_probe$postgresql$clog__checkpoint__done$v1$63686172(char);
extern int __dtrace_isenabled$postgresql$clog__checkpoint__done$v1(void);
extern void __dtrace_probe$postgresql$clog__checkpoint__start$v1$63686172(char);
extern int __dtrace_isenabled$postgresql$clog__checkpoint__start$v1(void);
extern void __dtrace_probe$postgresql$deadlock__found$v1(void);
extern int __dtrace_isenabled$postgresql$deadlock__found$v1(void);
extern void __dtrace_probe$postgresql$lock__wait__done$v1$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int);
extern int __dtrace_isenabled$postgresql$lock__wait__done$v1(void);
extern void __dtrace_probe$postgresql$lock__wait__start$v1$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int);
extern int __dtrace_isenabled$postgresql$lock__wait__start$v1(void);
extern void __dtrace_probe$postgresql$lwlock__acquire$v1$696e74$696e74(int, int);
extern int __dtrace_isenabled$postgresql$lwlock__acquire$v1(void);
extern void __dtrace_probe$postgresql$lwlock__condacquire$v1$696e74$696e74(int, int);
extern int __dtrace_isenabled$postgresql$lwlock__condacquire$v1(void);
extern void __dtrace_probe$postgresql$lwlock__condacquire__fail$v1$696e74$696e74(int, int);
extern int __dtrace_isenabled$postgresql$lwlock__condacquire__fail$v1(void);
extern void __dtrace_probe$postgresql$lwlock__release$v1$696e74(int);
extern int __dtrace_isenabled$postgresql$lwlock__release$v1(void);
extern void __dtrace_probe$postgresql$lwlock__wait__done$v1$696e74$696e74(int, int);
extern int __dtrace_isenabled$postgresql$lwlock__wait__done$v1(void);
extern void __dtrace_probe$postgresql$lwlock__wait__start$v1$696e74$696e74(int, int);
extern int __dtrace_isenabled$postgresql$lwlock__wait__start$v1(void);
extern void __dtrace_probe$postgresql$multixact__checkpoint__done$v1$63686172(char);
extern int __dtrace_isenabled$postgresql$multixact__checkpoint__done$v1(void);
extern void __dtrace_probe$postgresql$multixact__checkpoint__start$v1$63686172(char);
extern int __dtrace_isenabled$postgresql$multixact__checkpoint__start$v1(void);
extern void __dtrace_probe$postgresql$query__done$v1$63686172202a(const char *);
extern int __dtrace_isenabled$postgresql$query__done$v1(void);
extern void __dtrace_probe$postgresql$query__execute__done$v1(void);
extern int __dtrace_isenabled$postgresql$query__execute__done$v1(void);
extern void __dtrace_probe$postgresql$query__execute__start$v1(void);
extern int __dtrace_isenabled$postgresql$query__execute__start$v1(void);
extern void __dtrace_probe$postgresql$query__parse__done$v1$63686172202a(const char *);
extern int __dtrace_isenabled$postgresql$query__parse__done$v1(void);
extern void __dtrace_probe$postgresql$query__parse__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$postgresql$query__parse__start$v1(void);
extern void __dtrace_probe$postgresql$query__plan__done$v1(void);
extern int __dtrace_isenabled$postgresql$query__plan__done$v1(void);
extern void __dtrace_probe$postgresql$query__plan__start$v1(void);
extern int __dtrace_isenabled$postgresql$query__plan__start$v1(void);
extern void __dtrace_probe$postgresql$query__rewrite__done$v1$63686172202a(const char *);
extern int __dtrace_isenabled$postgresql$query__rewrite__done$v1(void);
extern void __dtrace_probe$postgresql$query__rewrite__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$postgresql$query__rewrite__start$v1(void);
extern void __dtrace_probe$postgresql$query__start$v1$63686172202a(const char *);
extern int __dtrace_isenabled$postgresql$query__start$v1(void);
extern void __dtrace_probe$postgresql$smgr__md__read__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74$696e74$696e74(int, unsigned int, unsigned int, unsigned int, unsigned int, int, int, int);
extern int __dtrace_isenabled$postgresql$smgr__md__read__done$v1(void);
extern void __dtrace_probe$postgresql$smgr__md__read__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74(int, unsigned int, unsigned int, unsigned int, unsigned int, int);
extern int __dtrace_isenabled$postgresql$smgr__md__read__start$v1(void);
extern void __dtrace_probe$postgresql$smgr__md__write__done$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74$696e74$696e74(int, unsigned int, unsigned int, unsigned int, unsigned int, int, int, int);
extern int __dtrace_isenabled$postgresql$smgr__md__write__done$v1(void);
extern void __dtrace_probe$postgresql$smgr__md__write__start$v1$696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74$696e74(int, unsigned int, unsigned int, unsigned int, unsigned int, int);
extern int __dtrace_isenabled$postgresql$smgr__md__write__start$v1(void);
extern void __dtrace_probe$postgresql$sort__done$v1$63686172$6c6f6e67(char, long);
extern int __dtrace_isenabled$postgresql$sort__done$v1(void);
extern void __dtrace_probe$postgresql$sort__start$v1$696e74$63686172$696e74$696e74$63686172(int, char, int, int, char);
extern int __dtrace_isenabled$postgresql$sort__start$v1(void);
extern void __dtrace_probe$postgresql$statement__status$v1$63686172202a(const char *);
extern int __dtrace_isenabled$postgresql$statement__status$v1(void);
extern void __dtrace_probe$postgresql$subtrans__checkpoint__done$v1$63686172(char);
extern int __dtrace_isenabled$postgresql$subtrans__checkpoint__done$v1(void);
extern void __dtrace_probe$postgresql$subtrans__checkpoint__start$v1$63686172(char);
extern int __dtrace_isenabled$postgresql$subtrans__checkpoint__start$v1(void);
extern void __dtrace_probe$postgresql$transaction__abort$v1$756e7369676e656420696e74(unsigned int);
extern int __dtrace_isenabled$postgresql$transaction__abort$v1(void);
extern void __dtrace_probe$postgresql$transaction__commit$v1$756e7369676e656420696e74(unsigned int);
extern int __dtrace_isenabled$postgresql$transaction__commit$v1(void);
extern void __dtrace_probe$postgresql$transaction__start$v1$756e7369676e656420696e74(unsigned int);
extern int __dtrace_isenabled$postgresql$transaction__start$v1(void);
extern void __dtrace_probe$postgresql$twophase__checkpoint__done$v1(void);
extern int __dtrace_isenabled$postgresql$twophase__checkpoint__done$v1(void);
extern void __dtrace_probe$postgresql$twophase__checkpoint__start$v1(void);
extern int __dtrace_isenabled$postgresql$twophase__checkpoint__start$v1(void);
extern void __dtrace_probe$postgresql$wal__buffer__write__dirty__done$v1(void);
extern int __dtrace_isenabled$postgresql$wal__buffer__write__dirty__done$v1(void);
extern void __dtrace_probe$postgresql$wal__buffer__write__dirty__start$v1(void);
extern int __dtrace_isenabled$postgresql$wal__buffer__write__dirty__start$v1(void);
extern void __dtrace_probe$postgresql$xlog__insert$v1$756e7369676e65642063686172$756e7369676e65642063686172(unsigned char, unsigned char);
extern int __dtrace_isenabled$postgresql$xlog__insert$v1(void);
extern void __dtrace_probe$postgresql$xlog__switch$v1(void);
extern int __dtrace_isenabled$postgresql$xlog__switch$v1(void);

#else

#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_FLUSH_DONE(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_FLUSH_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_FLUSH_START(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_FLUSH_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_READ_DONE(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_READ_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_READ_START(arg0, arg1, arg2, arg3, arg4, arg5, arg6) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_READ_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_DONE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_START(arg0, arg1) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_CHECKPOINT_DONE(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_CHECKPOINT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_CHECKPOINT_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_CHECKPOINT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_CLOG_CHECKPOINT_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_CLOG_CHECKPOINT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_DEADLOCK_FOUND() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_DEADLOCK_FOUND_ENABLED() (0)
#define	TRACE_POSTGRESQL_LOCK_WAIT_DONE(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_LOCK_WAIT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_LOCK_WAIT_START(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_LOCK_WAIT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_LWLOCK_ACQUIRE(arg0, arg1) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_ACQUIRE_ENABLED() (0)
#define	TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE(arg0, arg1) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_ENABLED() (0)
#define	TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL(arg0, arg1) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL_ENABLED() (0)
#define	TRACE_POSTGRESQL_LWLOCK_RELEASE(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_RELEASE_ENABLED() (0)
#define	TRACE_POSTGRESQL_LWLOCK_WAIT_DONE(arg0, arg1) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_WAIT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_LWLOCK_WAIT_START(arg0, arg1) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_LWLOCK_WAIT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_DONE(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_EXECUTE_DONE() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_EXECUTE_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_EXECUTE_START() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_EXECUTE_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_PARSE_DONE(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_PARSE_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_PARSE_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_PARSE_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_PLAN_DONE() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_PLAN_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_PLAN_START() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_PLAN_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_REWRITE_DONE(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_REWRITE_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_REWRITE_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_REWRITE_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_QUERY_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_QUERY_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_SMGR_MD_READ_DONE(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_SMGR_MD_READ_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_SMGR_MD_READ_START(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_SMGR_MD_READ_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_SMGR_MD_WRITE_START(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_SMGR_MD_WRITE_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_SORT_DONE(arg0, arg1) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_SORT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_SORT_START(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_SORT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_STATEMENT_STATUS(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_STATEMENT_STATUS_ENABLED() (0)
#define	TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_TRANSACTION_ABORT(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_TRANSACTION_ABORT_ENABLED() (0)
#define	TRACE_POSTGRESQL_TRANSACTION_COMMIT(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_TRANSACTION_COMMIT_ENABLED() (0)
#define	TRACE_POSTGRESQL_TRANSACTION_START(arg0) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_TRANSACTION_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE_ENABLED() (0)
#define	TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START_ENABLED() (0)
#define	TRACE_POSTGRESQL_XLOG_INSERT(arg0, arg1) \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_XLOG_INSERT_ENABLED() (0)
#define	TRACE_POSTGRESQL_XLOG_SWITCH() \
do { \
	} while (0)
#define	TRACE_POSTGRESQL_XLOG_SWITCH_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H_TMP */
