.\" Copyright (c) 2016 Apple Inc.  All rights reserved.
.\"
.Dd March 11, 2016
.Dt HIDUTIL 1
.Sh NAME
.Nm hidutil
.Nd HID event system debug utility
.Sh SYNOPSIS
.Nm
.Op Ar command
.Op Ar options
.Sh DESCRIPTION
.Nm
Configure property, list devices and dumps stated of HID Evemt System
.Pp
Available commands and their options:
.Bl -tag -width "                "
.It Cm help
Print help message
.It Cm dump Ar <object> [options]
dump states of HID Event system object
.Bl -tag -width "                "
.It Objects:
.It Cm system
the entire HID system
.It Cm clients
all clients of the HID system
.It Cm services
all services in the HID system
.It Options:
.It Fl o Ar file , Fl Fl output Ar file
output to file [default: stdout]
.It Fl f Ar format , Fl Fl format Ar format
display data in specified format (xml or text) [default: xml]
.El
.It Cm property Ar <options>
Set/Get HID Event System or HID Event Sercvice property
.Bl -tag -width "                "
.It Options:
.It Fl Fl set Ar dictionary
Set property (key/value pair JSON style dictionary)
.It Fl Fl get Ar dictionary
Get property with key (where key is string value)
.It Fl Fl filter Ar dictionary
Filter services by properties (key/value pair JSON style dictionary)
.El
.It Cm list Ar <options>
Set/Get HID Event System or HID Event Sercvice property
.Bl -tag -width "                "
.It Options:
.It Fl Fl filter Ar dictionary
Filter services by properties (key/value pair JSON style dictionary)
.El
.El
.Sh PROPERTY
.Bl -tag -width "                "
.It Do ProductID Dc Li - numeric value (decimal or hex)
.It Do VendorID Dc Li - numeric value (decimal or hex)
.It Do LocationID Dc Li - numeric value (decimal or hex)
.It Do PrimaryUsagePage Dc Li - numeric value (decimal or hex)
.It Do PrimaryUsage Dc Li - numeric value (decimal or hex)
.It Do Trasport Dc Li - string value
.It Do Product Dc Li - string value
.El
.Sh SAMPLE USAGE
.Nm
dump system
.Fl o
system.plist
.Fl f
xml
.Pp
.Nm
property --filter '{"ProductID":0x54c}' --get "HIDPointerAcceleration"
.Pp
.Nm
property --filter '{"ProductID":0x54c, "VendorID":746}' --set '{"HIDPointerAcceleration":0}'
.Pp
.Nm
list
.Pp
.Nm
list --filter '{"VendorID":0x54c}'
